### ISSUE TITLE
Mysql db access error

### ISSUE THREAD

**Issue by Hmarionx** [Ejdamm/bristle#2]
Hello,
There's a problem when php tries to connect to mysql database.
In my apache log I got : 
[:error] [pid 24983] [client xxxxxxxxx] PHP Warning:  array_merge(): Argument #2 is not an array in xxx/bristle/lib/Database/CDatabaseBasic.php on line 60
[:error] [pid 24983] [client xxxxxxxxx] PHP Fatal error:  Uncaught Exception: You can not connect, missing dsn. in xxx/bristle/lib/Database/CDatabaseBasic.php:112\nStack trace:\n#0 xxx/bristle/src/db.php(13): Mos\\Database\\CDatabaseBasic->connect()\n#1 xxx/bristle/index.php(5): DB_QUERY->__construct()\n#2 {main}\n  thrown in xxx/bristle/lib/Database/CDatabaseBasic.php on line 112

Older version of bristle still access to the database, and conf.php is correctly setup.
I use Apache/2.4.18 / mysql  5.7.21 / PHP 7.0.22

**Comment by adamgeorgsson** [comment]
Seems like I forgot to update the new conf.php.example with what I had in conf.php. Sorry for the inconvenience and hope it works better now.

**Comment by Hmarionx** [comment]
Yes indeed, it works better. Thanks for the fix !  You can close this issue.
Just another thing, in /style login.css is style called but doesn't exists in branch. Get 404 error in log, I've just fixed it by adding a login.css empty file.
Thanks for your work, it's a very good job

**Comment by adamgeorgsson** [comment]
I deleted the login files since I don't have any login system(yet) and forgot to delete the include in common.css. I will remove it in the next commit.
