### ISSUE TITLE
viewing filtered events

### ISSUE THREAD

**Issue by sergioMITM** [Ejdamm/bristle#3]
I ran across an issue where I try to view the details of an event when it's filtered. When I click the details of an event I lose my filter.

For instance, if I go to: https://sergiomitm.com/bristle/events.php and filter for SSH scans, I get a urls like this:
https://sergiomitm.com/bristle/events.php?ip_src=&ip_dst=&sig_name=ssh+scan&submit=Filter&filter=-

If I click the first event to view details, the resulting url is:
https://sergiomitm.com/bristle/events.php?filter=-&sid=1&cid=1208628
which just shows my most recent events, not the details of the item I was hoping for.

If I combine the parameters of the last two options, I get what I was hoping for
https://sergiomitm.com/bristle/events.php?ip_src=&ip_dst=&sig_name=ssh+scan&submit=Filter&filter=-&sid=1&cid=1208628

Let me know if this needs any clarification, hopefully it's an easy thing to deal with.

**Comment by adamgeorgsson** [comment]
It should be fixed now and as a bonus some other similar bugs got fixed too. Thank you for reporting!

**Comment by sergioMITM** [comment]
thx! works like a charm
